POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRpbWJsZSIsImlkIjoiNjQ4MmJlMGQ4ZWZkZmIxZmJmNWMxYTI4IiwiaWF0IjoxNjg2MjkxMTM0fQ.6C77agg2d5iOeb7jbjxK5y6CNC1z-KXRUorJL8Gy8tQ

{
  "title": "Dim bim bom",
  "author": "bouuuuu",
  "url": "www.uiuiuiuijijjjij.com",
  "likes": 5
}